const functions = require('firebase-functions');
const { onDocumentCreated } = require('firebase-functions/v2/firestore');
const { onRequest } = require('firebase-functions/v2/https');
const nodemailer = require('nodemailer');

// Configure email transporter
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: functions.config().email && functions.config().email.user || 'your-email@gmail.com',
        pass: functions.config().email && functions.config().email.pass || 'your-app-password'
    }
});

// Function that triggers when a new contact message is created
exports.sendContactEmail = onDocumentCreated({
    document: 'contact_messages/{messageId}',
    region: 'asia-northeast1'
}, async (event) => {
    try {
        const messageData = event.data.data();
        const messageId = event.params.messageId;
        
        console.log(`New contact message received: ${messageId}`);
        
        const mailOptions = {
            from: functions.config().email && functions.config().email.user || 'your-email@gmail.com',
            to: 'tsangkaho12@gmail.com',
            subject: 'New Contact Form Submission - Kaho Tsang Portfolio',
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                    <h2 style="color: #008080;">New Contact Form Submission</h2>
                    <div style="background-color: #f5f7fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
                        <h3 style="color: #1f2d47; margin-top: 0;">Contact Details</h3>
                        <p><strong>Name:</strong> ${messageData.name}</p>
                        <p><strong>Email:</strong> <a href="mailto:${messageData.email}">${messageData.email}</a></p>
                        <p><strong>Date:</strong> ${messageData.timestamp ? messageData.timestamp.toDate().toLocaleString() : 'N/A'}</p>
                        <p><strong>IP Address:</strong> ${messageData.ip || 'Unknown'}</p>
                    </div>
                    
                    <div style="background-color: #ffffff; padding: 20px; border-left: 4px solid #008080; margin: 20px 0;">
                        <h3 style="color: #1f2d47; margin-top: 0;">Message</h3>
                        <p style="line-height: 1.6; white-space: pre-wrap;">${messageData.message}</p>
                    </div>
                    
                    <div style="background-color: #e8f5e8; padding: 15px; border-radius: 5px; margin: 20px 0;">
                        <p style="margin: 0; color: #2d5a2d;">
                            <strong>Quick Actions:</strong><br>
                            • <a href="mailto:${messageData.email}?subject=Re: Your message from Kaho Tsang Portfolio">Reply directly to ${messageData.name}</a><br>
                            • <a href="https://console.firebase.google.com/project/kahotsang-portfolio/firestore/data/contact_messages/${messageId}">View in Firebase Console</a>
                        </p>
                    </div>
                    
                    <hr style="border: none; border-top: 1px solid #e1e5e9; margin: 30px 0;">
                    <p style="color: #666666; font-size: 12px;">
                        This email was automatically generated by your portfolio contact form.<br>
                        Message ID: ${messageId}
                    </p>
                </div>
            `
        };
        
        const result = await transporter.sendMail(mailOptions);
        console.log(`Email sent successfully to tsangkaho12@gmail.com for message ${messageId}`);
        
        return result;
        
    } catch (error) {
        console.error('Error sending email:', error);
        throw error;
    }
});

// HTTP function to test email sending
exports.testEmail = onRequest({
    region: 'asia-northeast1'
}, async (req, res) => {
    try {
        const testData = {
            name: 'Test User',
            email: 'test@example.com',
            message: 'This is a test message from the Firebase Function.',
            timestamp: new Date(),
            ip: req.ip
        };
        
        const mailOptions = {
            from: functions.config().email && functions.config().email.user || 'your-email@gmail.com',
            to: 'tsangkaho12@gmail.com',
            subject: 'Test Email - Kaho Tsang Portfolio',
            html: `
                <h2>Test Email</h2>
                <p>This is a test email to verify the Firebase Function is working.</p>
                <p><strong>Name:</strong> ${testData.name}</p>
                <p><strong>Email:</strong> ${testData.email}</p>
                <p><strong>Message:</strong> ${testData.message}</p>
            `
        };
        
        const result = await transporter.sendMail(mailOptions);
        res.json({ success: true, messageId: result.messageId });
        
    } catch (error) {
        console.error('Test email error:', error);
        res.status(500).json({ error: error.message });
    }
}); 